name: CustomAnvil
version: 1.0
description: Allows you to combine items without worrying losing the lores!
author: RedEpic
website: http://dev.bukkit.org/bukkit-plugins/CustomAnvil/
main: me.redepic.customanvil.CustomAnvil
